#spring.application.name=53-03-SB-REST-EMP-CRUD
#spring.main.banner-mode=off
server.port = 8080

# MYSQL Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3300/mydb
#spring.datasource.username=root
#spring.datasource.password=root

#JPA Properties
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibnernate.format_sql = true
#spring.jpa.hibernate.ddl-auto=update