spring:
  application:
    name: 74-75-SBRestSpringRedisCache
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3300/mydb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
     host: localhost
     port: 6379
server:
  port: 8081

management:
 endpoint:
   health:
    show-details: always


